<h3>Video Slider</h3>
<p>Power builder makes it possible to create video sliders and video galleries with custom thumbnails and play buttons. 
</p>

<h4>Module Options</h4>
	<ul class="marked-list">
		<li>
            <dl class="inline-term">
                <dt>Admin Label </dt>
                <dd>
    				This will change the label of the video in the builder for easy identification.
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt>Video MP4/URL</dt>
                <dd>
    				Upload your desired video in .MP4 format, or type in the URL to the video you would like to display.
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt> Video Webm</dt>
                <dd>
                   Upload the .WEBM version of your video here. All uploaded videos should be in both .MP4 .WEBM formats to ensure maximum compatibility in all browsers.
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt>Image Overlay URL</dt>
                <dd>
                   Upload your desired image, or type in the URL to the image you would like to display over your video. You can also generate a still image from your video.
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt> Display Image Overlays on Main Video</dt>
                <dd>
                  This option will cover the player UI on the main video. This image can either be uploaded in each video setting or auto-generated by Divi.
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt> Arrows</dt>
                <dd>
                   This setting will turn on and off the navigation arrows.
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt> Slider Controls</dt>
                <dd>
                   This setting will let you choose to use the thumbnail track controls below the slider or dot navigation at the bottom of the slider.
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt>Disable on </dt>
                <dd>
    				This will disable the module on selected devices.
                </dd>
            </dl>
        </li>
        <li>
            <dl class="inline-term">
                <dt>Admin Label</dt>
                <dd>
                    This will change the label of the module in the builder for easy identification.
                </dd>
            </dl>
        </li>
	</ul>        