<h3>Elementor Plugin</h3>

<p><b>JetElements</b> is a plugin that adds extensive modules for Elementor live page builder, allowing to build different kinds of content with easiness and efficiency. </p>

<p>With <b>JetElements</b> You can add various custom blocks to your website’s page layout, containing additional modules, which are not included in the standard Elementor page builder elements bundle. </p>

<p>Use <b>JetElements</b> to extend Your content with 19 diverse modules, devised especially to add timers, pricing tables and advanced sliders to Your website’s pages. </p>

    <div class="alert alert-info">
        You can find the detailed documentation on JetElements plugin <a href="http://documentation.zemez.io/wordpress/index.php?project=jetelements" target="_blank">here</a>.</div>

<h5>Widgets Overview</h5>

<ul class="marked-list">
<p><li><a href="http://jetelements.zemez.io/advanced-carousel/" target="_blank"><b>Advanced Carousel</b></a>  module displays slides in an attractive way. You can display from 1 to 10 slides at one time using Advanced Carousel module, set versatile animation options, create vivid backgrounds, enrich slides content with clear typography. With Advanced Carousel you can create as many slides as you need to.</li></p>
<p><li><a href="http://jetelements.zemez.io/advanced-map/" target="_blank"><b>Advanced Map</b></a>  module is the perfect solution if you need to display a map on your website, and add pins to it to locate the places. You can add multiple pins, change map style, enable switching from satellite to map view. The module is easily customizable and has friendly user interface.</li></p>
<p><li><a href="http://jetelements.zemez.io/animated-box/" target="_blank"><b>Animated Box</b></a>  module creates an attractive info block on the website’s page, which consists of two sides, that switch from one to other. You can add icons, buttons, titles and content to the animated box. Every element is easily customizable.</li></p>
<p><li><a href="http://jetelements.zemez.io/animated-text/" target="_blank"><b>Animated Text</b></a> module was specially devised to deliver your ideas in the form of attractively animated text. With the help of ths module you can add animated words and phrases to your website’s pages, customize them, and add plain text to complement animated text.</li></p>
<p><li><a href="http://jetelements.zemez.io/banner/" target="_blank"><b>Banner</b></a> module allows you to add custom banners to your website’s content. The module has multiple style settings, that include animation settings. It provides you with the means to customize banner background, title and content.</li></p>
<p><li><a href="http://jetelements.zemez.io/brands/" target="_blank"><b>Brands</b></a> module helps you to showcase brands and companies on your website’s page. You can add brands, visualize them using brand logos, apply links to them, and customize them in the matter of several clicks.</li></p>
<p><li><a href="http://jetelements.zemez.io/button/" target="_blank"><b>Button</b></a> module will assist you in creating buttons with your custom text and links, eye-catching icons and versatile hover effects! With this module you can easily add a button whenever you need it and style it up according to your vision!</li></p>
<p><li><a href="http://jetelements.zemez.io/circle-progress/" target="_blank"><b>Circle Progress</b></a> module allows you to display progress in the attractive form of circle progress bar. The module has versatile style settings, such as content style, value type, etc.</li></p>
<p><li><a href="http://jetelements.zemez.io/countdown-timer/" target="_blank"><b>Countdown Timer</b></a> module is a helpful tool if you need to embed a timer with a countdown to your website’s page. The module has multiple settings, such as digits color, font settings, and custom background for the timer.</li></p>
<p><li><a href="http://jetelements.zemez.io/download-button/" target="_blank"><b>Download Button</b></a> module will assist You in creating versatile buttons that will allow the visitors downloading files in one click! You won't need to install additional plugins to add this kind of functionality to the website! All You need is to use Download Button module and have the file stored in the Media Library!</li></p>
<p><li><a href="http://jetelements.zemez.io/headline/" target="_blank"><b>Headline</b></a> module is the perfect tool for creating stunningly beautiful headlines in order to decorate the website’s pages with attractive textual titles. Its content is fully flexible, as well as its multiple style settings, devised to assist you in creating really beautiful headings within minutes! </li></p>
<p><li><a href="http://jetelements.zemez.io/image-comparison/" target="_blank"><b>Image Comparison</b></a> module is the perfect tool that will assist you in creating slides with image comparisons in an attractive and stylish way. From now on you wield the power to showcase the results of your work in an engaging Before and After form! </li></p>
<p><li><a href="http://jetelements.zemez.io/instagram/" target="_blank"><b>Instagram</b></a> module mpowers you to showcase Instagram publications on yuor website's pages in an attractive way, with text captions, meta information (the number of likes and comments). You'll be able to style up this module according to your vision in order to make it the truly outstanding part of your website! </li></p>
<p><li><a href="http://jetelements.zemez.io/images-justify-layout/" target="_blank"><b>Images Layout</b></a> module displays images using different eye-catching layout types, such as Masonry, Justify or List. Add images and customize layouts in several clicks to get the stunning results and adorn Your website pages with beautiful imagery!</li></p>
<p><li><a href="http://jetelements.zemez.io/posts-grid/" target="_blank"><b>Posts</b></a> module is a multipurpose tool, that can create attractive post grid layouts, sort posts by categories, IDs or the date of publishing. This module is also helpful when creating post sliders and post carousels.</li></p>
<p><li><a href="http://jetelements.zemez.io/pricing-table/" target="_blank"><b>Pricing Table</b></a> module is helpful beyond measures when you need to showcase the prices and services your company provides in an attractive and clear way. The module has multiple options, versatile customization settings, and is easy to use.</li></p>
<p><li><a href="http://jetelements.zemez.io/scroll-navigation/" target="_blank"><b>Scroll Navigation</b></a> module has multiple style and content settings, allowing to set icons, use labels, define the elements position, background type, and there is so much more for you to customize to make the module look its best! </li></p>
<p><li><a href="http://jetelements.zemez.io/services/" target="_blank"><b>Services</b></a> module is devised to add attractive services blocks to your website pages in a smooth and easy way! Use it to showcase the services provided by your company. With Services module you can manage the service title, description, and there are still lots of style settings you can manage. </li></p>
<p><li><a href="http://jetelements.zemez.io/slider/" target="_blank"><b>Slider</b></a> module is invaluable if You need to liven up Your website page with a bright and attractive slider! This module is easily customizable, has multiple navigation options. It provides profound content and style settings, which make working on slider as simple as it can be!</li></p>
<p><li><a href="http://jetelements.zemez.io/team-members/" target="_blank"><b>Team Member</b></a> module is the perfect solution when it comes to displaying your team members, and if you need to introduce your team to your website visitors. There are multiple content and style settings, that can be changed at will! </li></p>
<p><li><a href="http://jetelements.zemez.io/testimonials/" target="_blank"><b>Testimonials</b></a> module is useful beyond compare when it comes to adding your clients’ positive feedbacks to your site. Feel free to style up the testimonials and add the beautiful testimonials carousel right to your web page in several clicks! </li></p>
<p><li><a href="http://jetelements.zemez.io/recent-products/" target="_blank"><b>WooCommerce Recent Products</b></a> module helps you to showcase the products on your website’s page and sort them using custom order.</li></p>
<p><li><a href="http://jetelements.zemez.io/featured-products/" target="_blank"><b>WooCommerce Featured Products</b></a> module helps you to display featured products in an attractive way on your website’s page, and sort them using custom order.</li></p>
<p><li><a href="http://jetelements.zemez.io/sale-products/" target="_blank"><b>WooCommerce Sale Products</b></a> helps you to display sale products on your website’s page, and sort them using custom order.</li></p>
<p><li><a href="http://jetelements.zemez.io/best-sellers/" target="_blank"><b>WooCommerce Best Sellers</b></a> module is extremely helpful if you need to show the most sold products on your website’s page, and arrange them in columns.</li></p>
<p><li><a href="http://jetelements.zemez.io/top-products/" target="_blank"><b>WooCommerce Top Rated Products</b></a> module can be used if you want to showcase the products that have the highest rating according to the customers reviews. With this module you can set the number of products to show per page and the number of columns in which the products will be organized.</li></p>
<p><li><a href="http://jetelements.zemez.io/wc-products/" target="_blank"><b>WooCommerce Product</b></a> module can help you to display custom products on your website page in a classy way.</li></p>
<p><li><a href="http://jetelements.zemez.io/contact-form-7/" target="_blank"><b>Contact Form 7</b></a> module helps you to display your existing contact forms. You have to create a contact form using Contact Form 7 plugin before placing it to your website’s page.</li></p>
<p><li><a href="http://jetelements.zemez.io/subscribe-form/" target="_blank"><b>Subscribe Form</b></a> module will assist you in creating a Subscription form that works work with your MailChimp list. This module is really easy to use, allowing to change the Subscription form layout, background color, width, add borders, shadows, and there are still many more exquisite options.</li></p>
<p><li><a href="http://jetelements.zemez.io/portfolio/" target="_blank"><b>Portfolio </b></a> module displays Portfolio in the form of eye-catching layouts using the pre-designed presets and masonry, grid, justify and list layout types!</li></p>
<p><li><a href="http://jetelements.zemez.io/parallax/" target="_blank"><b>Parallax effect </b></a> makes it easy to create a parallax effect for sections with multiple adjustable layers and attractively looking backgrounds!</li></p>
<p><li><a href="http://jetelements.zemez.io/progressbars/" target="_blank"><b>Progress Bars</b></a> is the top-notch tool that will assist in creating stylish animated progress bars, which are really easy to customize!</li></p>
</ul>
